model:
  model_name: "wav2vec-mini-finetuned" 
  model_dimensions: 768

training:
  epochs: 10
  batch_size: 8
  learning_rate: 3e-4

logging:
  save_checkpoint_every: 1 
  checkpoint_dir: "./checkpoints"