model:
  model_name: "wav2vec-mini" 
  model_dimensions: 768

training:
  epochs: 20
  batch_size: 16
  learning_rate: 3e-4

logging:
  log_interval: 100
  save_checkpoint_every: 1 
  checkpoint_dir: "./checkpoints"